// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_T_cpp
Eigen::MatrixXd compute_T_cpp(const Eigen::MatrixXd& sig_eps_inv_T, const Eigen::MatrixXd& phi_sig_xi_sqrt);
RcppExport SEXP _dearseq_compute_T_cpp(SEXP sig_eps_inv_TSEXP, SEXP phi_sig_xi_sqrtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type sig_eps_inv_T(sig_eps_inv_TSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type phi_sig_xi_sqrt(phi_sig_xi_sqrtSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_T_cpp(sig_eps_inv_T, phi_sig_xi_sqrt));
    return rcpp_result_gen;
END_RCPP
}
// perm_list_cpp
Rcpp::List perm_list_cpp(const Rcpp::IntegerVector& indiv, const int nb_indiv, const int n, const int n_perm, const Rcpp::IntegerVector& o);
RcppExport SEXP _dearseq_perm_list_cpp(SEXP indivSEXP, SEXP nb_indivSEXP, SEXP nSEXP, SEXP n_permSEXP, SEXP oSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type indiv(indivSEXP);
    Rcpp::traits::input_parameter< const int >::type nb_indiv(nb_indivSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type o(oSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_list_cpp(indiv, nb_indiv, n, n_perm, o));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dearseq_compute_T_cpp", (DL_FUNC) &_dearseq_compute_T_cpp, 2},
    {"_dearseq_perm_list_cpp", (DL_FUNC) &_dearseq_perm_list_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_dearseq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
