# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_T_cpp <- function(sig_eps_inv_T, phi_sig_xi_sqrt) {
    .Call(`_dearseq_compute_T_cpp`, sig_eps_inv_T, phi_sig_xi_sqrt)
}

perm_list_cpp <- function(indiv, nb_indiv, n, n_perm, o) {
    .Call(`_dearseq_perm_list_cpp`, indiv, nb_indiv, n, n_perm, o)
}

